- id: skopos-check
  name: skopos-check
  description: "Runs skopos behavioral analysis on dependencies."
  entry: skopos check
  language: python
  types: [text]
  files: ^(pyproject\.toml|requirements\.txt)$
